server:
  port: 8080

spring:
  sleuth:
    sampler:
      probability: 1.0  # 采样率(1.0表示100%)
  zipkin:
    base-url: http://localhost:9411/   # 你的 Zipkin Server 地址
    sender:
      type: web
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**