server:
  port: 8082
spring:
  sleuth:
    sampler:
      probability: 1.0  # 采样率(1.0表示100%)
  zipkin:
    base-url: http://localhost:9411/   # 你的 Zipkin Server 地址
    sender:
      type: web                        # 用 HTTP 方式上报